name: Project Tests
on:
  push:
    branches:
      - 4.0
  pull_request:
    branches:
      - 4.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.13
      - name: Install dependencies
        run: python3 setup.py install
      - name: Test with Indices
        run: python3 -m unittest tests/indices_test.py
      - name: Test with Stocks
        run: python3 -m unittest tests/stocks_test.py
